name:  "myGivTCP"
description:  "TCP Modbus connection to MQTT/JSON for Givenergy Battery/PV Invertors"
version:  "3.5.2"
image: RogueCarbon:dev_giv_tcp
slug:  "mygivtcp"
homeassistant_api: true
hassio_api: true
init:  true
ingress: true
services:
  - "mqtt:want"
map:
  - config:rw
  - ssl
boot:  auto
url:  https://github.com/RogueCarbon/dev_giv_tcp
legacy:  true
arch: 
  - aarch64
  - amd64
host_network: true

